import 'dart:io';
import 'package:clean_solid_cli_mobile/models/field.dart';

class SqlGenerator {
  static int _migrationCounter = 0;
  /// Génère la migration SQL.
  /// [isUpdate] = true si appelé depuis cscm implemente (ALTER TABLE)
  /// [isUpdate] = false si appelé depuis cscm create (CREATE TABLE)
  static void generateMigration({
    required String featureName,
    required List<Field> fields,
    bool isUpdate = false,
  }) {
    final tableName = '${featureName.toLowerCase()}s';
    final timestamp = DateTime.now().millisecondsSinceEpoch;
    final migrationsDir = 'supabase/migrations';

    final dir = Directory(migrationsDir);
    if (!dir.existsSync()) {
      dir.createSync(recursive: true);
    }

    final String content;
    final String fileName;

    if (isUpdate) {
      content = _buildAlterTableSql(tableName, fields);
      fileName = '${timestamp}_alter_${tableName}_add_columns.sql';
    } else {
      content = _buildCreateTableSql(tableName, fields);
      fileName = '${timestamp}_create_${tableName}.sql';
    }

    final filePath = '$migrationsDir/$fileName';
    var finalPath = filePath;
    var finalFileName = fileName;
    final file = File(finalPath);
    if (file.existsSync()) {
      _migrationCounter++;
      finalFileName = '${timestamp}_${_migrationCounter}${isUpdate ? "_alter" : "_create"}_${tableName}.sql';
      finalPath = '$migrationsDir/$finalFileName';
    }

    file.writeAsStringSync(content);
    print('  Migration SQL générée : $finalFileName');
  }

  // ═══════════════════════════════════════════════════
  // CREATE TABLE (nouvelle feature)
  // ═══════════════════════════════════════════════════

  static String _buildCreateTableSql(String tableName, List<Field> fields) {
    final buffer = StringBuffer();

    buffer.writeln('-- ============================================');
    buffer.writeln('-- Migration: create_$tableName');
    buffer.writeln('-- Generated by CSCM — do not edit manually');
    buffer.writeln('-- ============================================');
    buffer.writeln();

    // Enums
    final enumFields = fields.where((f) => f.isEnum).toList();
    if (enumFields.isNotEmpty) {
      buffer.writeln('-- Enums');
      for (final f in enumFields) {
        final values = f.enumValues
            .map((v) => "'${v.toLowerCase()}'")
            .join(', ');
        buffer.writeln(
          "DO \$\$ BEGIN\n"
          "  CREATE TYPE ${f.snakeName} AS ENUM ($values);\n"
          "EXCEPTION\n"
          "  WHEN duplicate_object THEN null;\n"
          "END \$\$;",
        );
      }
      buffer.writeln();
    }

    // Table
    buffer.writeln('-- Table');
    buffer.write('CREATE TABLE IF NOT EXISTS $tableName (\n');
    buffer.write('  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,\n');

    for (var i = 0; i < fields.length; i++) {
      final f = fields[i];

      if (f.isEnum) {
        buffer.write(
          "  ${f.snakeName} ${f.snakeName}"
          " DEFAULT '${f.enumValues.first.toLowerCase()}',\n",
        );
      } else if (f.isReference) {
        final refTable = '${f.referenceTargetSnake}s';
        buffer.write(
          '  ${f.referenceIdSnake} UUID'
          " REFERENCES $refTable(id) ON DELETE SET NULL,\n",
        );
      } else {
        buffer.write('  ${f.snakeName} ${_toPostgresType(f.type)},\n');
      }
    }

    buffer.write('  created_at TIMESTAMPTZ DEFAULT now() NOT NULL\n');
    buffer.write(');\n\n');

    // Indexes
    _writeIndexes(buffer, tableName, fields);

    return buffer.toString();
  }

  // ═══════════════════════════════════════════════════
  // ALTER TABLE (mise à jour de feature)
  // ═══════════════════════════════════════════════════

  static String _buildAlterTableSql(String tableName, List<Field> fields) {
    final buffer = StringBuffer();

    buffer.writeln('-- ============================================');
    buffer.writeln('-- Migration: alter_${tableName}_add_columns');
    buffer.writeln('-- Generated by CSCM — do not edit manually');
    buffer.writeln('-- ============================================');
    buffer.writeln();

    // Enums (CREATE TYPE IF NOT EXISTS)
    final enumFields = fields.where((f) => f.isEnum).toList();
    if (enumFields.isNotEmpty) {
      buffer.writeln('-- New enum types');
      for (final f in enumFields) {
        final values = f.enumValues
            .map((v) => "'${v.toLowerCase()}'")
            .join(', ');
        buffer.writeln(
          "DO \$\$ BEGIN\n"
          "  CREATE TYPE ${f.snakeName} AS ENUM ($values);\n"
          "EXCEPTION\n"
          "  WHEN duplicate_object THEN null;\n"
          "END \$\$;",
        );
      }
      buffer.writeln();
    }

    // ALTER TABLE ADD COLUMN
    buffer.writeln('-- Add columns');
    for (final f in fields) {
      if (f.isEnum) {
        buffer.writeln(
          "ALTER TABLE $tableName ADD COLUMN IF NOT EXISTS"
          " ${f.snakeName} ${f.snakeName}"
          " DEFAULT '${f.enumValues.first.toLowerCase()}';",
        );
      } else if (f.isReference) {
        final refTable = '${f.referenceTargetSnake}s';
        buffer.writeln(
          "ALTER TABLE $tableName ADD COLUMN IF NOT EXISTS"
          " ${f.referenceIdSnake} UUID"
          " REFERENCES $refTable(id) ON DELETE SET NULL;",
        );
      } else {
        buffer.writeln(
          "ALTER TABLE $tableName ADD COLUMN IF NOT EXISTS"
          " ${f.snakeName} ${_toPostgresType(f.type)};",
        );
      }
    }
    buffer.writeln();

    // New indexes
    _writeIndexes(buffer, tableName, fields);

    return buffer.toString();
  }

  // ═══════════════════════════════════════════════════
  // UTILS
  // ═══════════════════════════════════════════════════

  static void _writeIndexes(
    StringBuffer buffer,
    String tableName,
    List<Field> fields,
  ) {
    final indexFields = fields.where((f) {
      if (f.isReference) return true;
      if (f.isEnum) return true;
      if (f.type == 'String') return true;
      return false;
    });

    if (indexFields.isNotEmpty) {
      buffer.writeln('-- Indexes');
      for (final f in indexFields) {
        final col = f.isReference ? f.referenceIdSnake : f.snakeName;
        buffer.write(
          'CREATE INDEX IF NOT EXISTS '
          'idx_${tableName}_$col ON $tableName($col);\n',
        );
      }
      buffer.writeln();
    }
  }

  static String _toPostgresType(String dartType) {
    switch (dartType) {
      case 'String':
        return 'TEXT';
      case 'int':
        return 'INTEGER';
      case 'double':
        return 'NUMERIC';
      case 'bool':
        return 'BOOLEAN';
      case 'DateTime':
        return 'TIMESTAMPTZ';
      default:
        return 'TEXT';
    }
  }
}
