name: clean_solid_cli_mobile
description: 'CLI tool for Clean Architecture + Solid Principle scaffolding in Flutter projects.'
version: 2.0.0
homepage: https://github.com/Rahkoja09/cleanSolidCLI
repository: https://github.com/Rahkoja09/cleanSolidCLI
documentation: https://github.com/Rahkoja09/cleanSolidCLI#readme
issue_tracker: https://github.com/Rahkoja09/cleanSolidCLI/issues
topics:
  - cli
  - flutter
  - clean-architecture
  - solid-principles
  - code-generator
  - scaffolding

environment:
  sdk: ^3.7.0

dependencies:
  path: ^1.8.0
  args: ^2.5.0
  yaml: ^3.1.2

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0

executables:
  cscm: main
