-- ============================================
-- Migration: create_sessions
-- Generated by CSCM — do not edit manually
-- ============================================

-- Table
CREATE TABLE IF NOT EXISTS sessions (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  is_connected BOOLEAN,
  current_tokken TEXT,
  remote_tokken TEXT,
  created_at TIMESTAMPTZ DEFAULT now() NOT NULL
);

-- Indexes
CREATE INDEX IF NOT EXISTS idx_sessions_current_tokken ON sessions(current_tokken);
CREATE INDEX IF NOT EXISTS idx_sessions_remote_tokken ON sessions(remote_tokken);

